language: node_js

env:
     - DB=postgresql://postgres@localhost:5432/reg_num
node_js:
        - "8.9.4"

before_script:
  # - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  # - sudo service postgresql restart
  - psql -c 'create database  reg_num;' -U postgres
  - psql -U postgres -d reg_num -a -f registration_table.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2




   # Name : DATABASE_URL
   # value : //postgres@localhost:5433/reg_num

# language: node_js
 # env: - DB=postgresql://postgres:postgres@localhost:5433/reg_num

# node_js:
#   - "8.9.4"

# before_script:
#
#     - sleep 1

    # - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';


  # addons:
  #   apt:
  #     packages:
  #     -postgresql-server-dev-9.2

# sudo: false
# dist: trusty
# addons:
#  apt:
#    packages:
#      - postgresql-9.5
#      - postgresql-client-9.5
#  postgresql: '9.5'
# env:
#  global:
#    - PGPORT=5433


  # postgresql: "9.5"

# services:
#   - postgresql




#     postgres:
#   adapter: postgresql
#   database: reg_num
#   username: postgres
# before_script:
#   - "psql -c 'create database reg_num;' -U postgres"
#   - "rake db:migrate"

  # before_script:
  # - psql -c 'create database travis;' -U postgres
  # - psql -c 'create database reg_num;' -U postgres
  # - psql -c '\i registration_table.sql;' -U postgres
  # - node ./registration_numbers.js -d postgresql://coder:1234@localhost:5432/reg_num

# language: node_js
# env:
#      'postgresql://coder:1234@localhost:5432/reg_num'
# node_js:
#   - "8.9.4"
#
#   before_script:
#   - psql -c 'create database travis;' -U postgres
#   - psql -c 'create database reg_num;' -U postgres
#   - psql -c "CREATE USER coder WITH PASSWORD 'coder123';" -U postgres
#   - psql -c '\i registration_table.sql;' -U postgres
#   - node ./registration_numbers.js -d postgresql://coder:1234@localhost:5432/reg_num
#
# addons:
#     apt:
#     packages:
#     - postgresql-server-dev-9.2
